from __future__ import annotations

import json
import math
from datetime import UTC, datetime
from pathlib import Path

import numpy as np
import pandas as pd

from risklens import evaluation as ev
from risklens.live_scoring import POST_FREEZE

MONITOR_FILE = "live_monitor.json"
MIN_FORECASTS = 20
COVERAGE_FLOOR = 0.90
KUPIEC_ALPHA = 0.05


def ticker_metrics(rows: pd.DataFrame, actual: np.ndarray, rolling_var: np.ndarray) -> dict:
    """Post-freeze calibration of one asset; `rows` are realized signal rows in date order."""
    n = len(rows)
    sigma_sq = rows["forecast_volatility"].to_numpy() ** 2
    metrics: dict = {"n_forecasts": n}
    if n == 0:
        return metrics | {"status": "insufficient_data"}
    for level, suffix in ((0.95, ""), (0.80, "_80"), (0.50, "_50")):
        inside = (actual >= rows[f"pi_lower{suffix}"].to_numpy()) & (
            actual <= rows[f"pi_upper{suffix}"].to_numpy()
        )
        metrics[f"coverage_{int(level * 100)}"] = float(inside.mean())
    _, metrics["kupiec_p_95"] = ev.kupiec_uc(
        (actual < rows["pi_lower"].to_numpy()) | (actual > rows["pi_upper"].to_numpy()), 0.05
    )
    metrics["qlike_garch"] = float(ev.qlike_loss(sigma_sq, actual**2).mean())
    metrics["qlike_rolling_21"] = float(ev.qlike_loss(rolling_var, actual**2).mean())
    metrics["vol_ratio"] = float(np.sqrt(np.mean(actual**2) / np.mean(sigma_sq)))
    if n < MIN_FORECASTS:
        return metrics | {"status": "insufficient_data"}
    watch = (
        metrics["coverage_95"] < COVERAGE_FLOOR
        or metrics["kupiec_p_95"] < KUPIEC_ALPHA
        or metrics["qlike_garch"] > metrics["qlike_rolling_21"]
    )
    return metrics | {"status": "watch" if watch else "ok"}


def realized_frame(signals: pd.DataFrame, market: pd.DataFrame, ticker: str) -> pd.DataFrame:
    rows = signals[(signals["ticker"] == ticker) & (signals["split"] == POST_FREEZE)]
    rows = rows.sort_values("date")
    m = market[market["ticker"] == ticker].set_index("date")
    return rows.assign(
        actual=m["log_return"].reindex(rows["date"]).to_numpy(),
        rolling_var=m["roll_vol_21"].reindex(rows["origin_date"]).to_numpy() ** 2,
    )


def build_monitor(signals: pd.DataFrame, market: pd.DataFrame, now: datetime | None = None) -> dict:
    tickers = {}
    for ticker in sorted(signals["ticker"].unique()):
        rows = realized_frame(signals, market, ticker)
        tickers[ticker] = ticker_metrics(
            rows, rows["actual"].to_numpy(), rows["rolling_var"].to_numpy()
        )
    return {
        "generated_at": (now or datetime.now(UTC)).astimezone(UTC).isoformat(timespec="seconds"),
        "rules": {
            "min_forecasts": MIN_FORECASTS,
            "coverage_floor_95": COVERAGE_FLOOR,
            "kupiec_alpha": KUPIEC_ALPHA,
        },
        "tickers": tickers,
    }


def _clean(value: object) -> object:
    if isinstance(value, dict):
        return {k: _clean(v) for k, v in value.items()}
    if isinstance(value, float) and not math.isfinite(value):
        return None
    return value


def write_monitor(monitor: dict, live_dir: Path) -> None:
    path = live_dir / MONITOR_FILE
    tmp = path.with_suffix(".json.tmp")
    tmp.write_text(json.dumps(_clean(monitor), indent=2), encoding="utf-8", newline="\n")
    tmp.replace(path)


def render_report(monitor: dict, status: dict | None, signals: pd.DataFrame) -> str:
    lines = [
        "# Live monitoring (post-freeze)",
        "",
        "Generated by `python -m risklens.live_pipeline` after each data refresh. Everything "
        "below is out of sample and after the frozen vintage; the sealed-test results in "
        "`test_results*.md` are unchanged. Models are scored, not retrained: parameters follow "
        "the pre-registered walk-forward refit, and thresholds come from the frozen configuration.",
        "",
    ]
    if status:
        lines += [
            f"Data state: **{status['state']}**, last close {status['last_close']} "
            f"(checked {status['checked_at']}).",
            "",
        ]
    rules = monitor["rules"]
    lines += [
        f"Status needs at least {rules['min_forecasts']} realized forecasts. `watch` means 95% "
        f"coverage below {rules['coverage_floor_95']:.0%}, Kupiec p below "
        f"{rules['kupiec_alpha']:.2f}, or QLIKE worse than the 21-day rolling baseline.",
        "",
        "| Asset | Forecasts | Coverage 95% | Coverage 80% | Coverage 50% | Kupiec p | "
        "QLIKE GARCH | QLIKE rolling | Vol ratio | Status |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]

    def cell(metrics: dict, key: str, fmt: str) -> str:
        value = metrics.get(key)
        return "n/a" if value is None else format(value, fmt)

    for ticker, m in monitor["tickers"].items():
        lines.append(
            f"| {ticker} | {m['n_forecasts']} | {cell(m, 'coverage_95', '.1%')} | "
            f"{cell(m, 'coverage_80', '.1%')} | {cell(m, 'coverage_50', '.1%')} | "
            f"{cell(m, 'kupiec_p_95', '.2f')} | {cell(m, 'qlike_garch', '.3f')} | "
            f"{cell(m, 'qlike_rolling_21', '.3f')} | {cell(m, 'vol_ratio', '.2f')} | "
            f"{m['status']} |"
        )
    latest = signals[signals["split"] == "live"].sort_values("ticker")
    lines += [
        "",
        "## Latest signals (experimental)",
        "",
        "| Asset | For | Signal | Risk | Forecast vol |",
    ]
    lines.append("|---|---|---|---|---|")
    for _, r in latest.iterrows():
        vol = r["forecast_volatility"] * float(np.sqrt(252)) * 100
        lines.append(
            f"| {r['ticker']} | {r['date']:%Y-%m-%d} | {r['signal']} | {r['risk_level']} | "
            f"{vol:.1f}% |"
        )
    lines.append("")
    return "\n".join(lines)
